promtail:
  config:
    logLevel: warn
    # Reduce CPU by batching logs less frequently
    clients:
      - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
        batchwait: 5s
        batchsize: 1048576
    positions:
      sync_period: 30s
    snippets:
      pipelineStages:
      - cri: {}
      - limit:
          burst: 100
          by_label_name: namespace
          drop: true
          rate: 100
