cilium:
  pmtuDiscovery:
    enabled: true
  cluster:
    name: default
  externalIPs:
    enabled: true
  ingressController:
    default: true
    enabled: true
    loadbalancerMode: shared
    service:
      annotations:
        io.cilium/lb-ipam-ips: 192.168.100.200
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: 10.42.0.0/16
  k8sClientRateLimit:
    burst: 200
    qps: 50
  k8sServiceHost: 192.168.100.5
  k8sServicePort: 6443
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  operator:
    replicas: 2
    rollOutPods: true
  rollOutCiliumPods: true
  routingMode: tunnel
  tunnelProtocol: vxlan
  # Reduce CPU usage
  monitor:
    aggregation: medium
  bpf:
    monitorAggregation: medium
    monitorInterval: 30s
    monitorFlags: all
